"""Display names for the 56-dataset text-tabular candidate pool.

The pool is keyed on the source-corpus enum names, while the paper's dataset tables are keyed
on the released MulTaBench enum names. The two differ in both the task prefix and the suffix,
so the map below is explicit. The 40 datasets that were released take their display name from
`do_dataset_summary`, the single source for every name the paper prints; the 16 that were
only ever candidates are named here.
"""
from multabench.scripts.do_dataset_summary import _FRIENDLY_NAMES, _FRIENDLY_NAMES_EXTRA_TEXT

# Pool (source-corpus) name -> released MulTaBench name.
POOL_TO_RELEASED = {
    "BIN_TEXT_FINANCIAL_CONSUMER_COMPLAINT":                "MUL_TEXT_CONSUMER_COMPLAINT",
    "BIN_TEXT_PROFESSIONAL_FAKE_JOB_POSTING":               "BIN_TEXT_FAKE_JOB_POSTING",
    "BIN_TEXT_PROFESSIONAL_KICKSTARTER_FUNDING":            "BIN_TEXT_KICKSTARTER_FUNDING",
    "BIN_TEXT_SOCIAL_IMDB_GENRE_PREDICTION":                "BIN_TEXT_IMDB_GENRE",
    "BIN_TEXT_SOCIAL_JIGSAW_TOXICITY":                      "BIN_TEXT_JIGSAW_TOXICITY",
    "BIN_TEXT_TRANSPORTATION_OSHA_ACCIDENT_INJURY_DATA":    "BIN_TEXT_OSHA_INJURY",
    "MUL_TEXT_CONSUMER_PRODUCT_SENTIMENT":                  "MUL_TEXT_PRODUCT_SENTIMENT",
    "MUL_TEXT_CONSUMER_WOMEN_ECOMMERCE_CLOTHING_REVIEW":    "MUL_TEXT_WOMEN_CLOTHING_REVIEW",
    "MUL_TEXT_FOOD_MICHELIN_GUIDE_RESTAURANTS":             "MUL_TEXT_MICHELIN_RESTAURANTS",
    "MUL_TEXT_FOOD_WINE_REVIEW":                            "MUL_TEXT_WINE_REVIEW",
    "MUL_TEXT_HOUSES_MELBOURNE_AIRBNB":                     "MUL_TEXT_MELBOURNE_AIRBNB",
    "MUL_TEXT_PROFESSIONAL_DATA_SCIENTIST_SALARY":          "MUL_TEXT_DATA_SCIENTIST_SALARY",
    "MUL_TEXT_SOCIAL_NEWS_CHANNEL_CATEGORY":                "MUL_TEXT_NEWS_CHANNEL",
    "MUL_TEXT_SOCIAL_SPOTIFY_GENRES":                       "MUL_TEXT_SPOTIFY_GENRES",
    "MUL_TEXT_TRANSPORTATION_US_ACCIDENTS_MARCH23":         "MUL_TEXT_US_ACCIDENTS",
    "REG_TEXT_CONSUMER_AMERICAN_EAGLE_PRICES":              "MUL_TEXT_AMERICAN_EAGLE_PRICES",
    "REG_TEXT_CONSUMER_BABIES_R_US_PRICES":                 "REG_TEXT_BABIES_PRICES",
    "REG_TEXT_CONSUMER_BOOK_PRICE_PREDICTION":              "REG_TEXT_BOOK_PRICE",
    "REG_TEXT_CONSUMER_MERCARI_ONLINE_MARKETPLACE":         "REG_TEXT_MERCARI_MARKETPLACE",
    "REG_TEXT_FOOD_ALCOHOL_WIKILIQ_PRICES":                 "REG_TEXT_WIKILIQ_PRICES",
    "REG_TEXT_FOOD_CHOCOLATE_BAR_RATINGS":                  "REG_TEXT_CHOCOLATE_BAR_RATINGS",
    "REG_TEXT_FOOD_RAMEN_RATINGS_2022":                     "REG_TEXT_RAMEN_RATINGS",
    "REG_TEXT_FOOD_WINE_POLISH_MARKET_PRICES":              "REG_TEXT_WINE_POLISH_MARKET",
    "REG_TEXT_FOOD_WINE_VIVINO_SPAIN":                      "REG_TEXT_WINE_VIVINO_SPAIN",
    "REG_TEXT_FOOD_ZOMATO_RESTAURANTS":                     "REG_TEXT_ZOMATO_RESTAURANTS",
    "REG_TEXT_HOUSES_AIRBNB_SEATTLE":                       "REG_TEXT_AIRBNB_SEATTLE",
    "REG_TEXT_HOUSES_CALIFORNIA_PRICES_2020":               "BIN_TEXT_CALIFORNIA_PRICES",
    "REG_TEXT_PROFESSIONAL_EMPLOYEE_RENUMERATION_VANCOUBER": "REG_TEXT_VANCOUVER_SALARIES",
    "REG_TEXT_PROFESSIONAL_EMPLOYEE_SALARY_MONTGOMERY":     "REG_TEXT_MONTGOMERY_SALARIES",
    "REG_TEXT_PROFESSIONAL_SCIMAGOJR_ACADEMIC_IMPACT":      "REG_TEXT_SCIMAGOJR_IMPACT",
    "REG_TEXT_SOCIAL_ANIME_PLANET_RATING":                  "REG_TEXT_ANIME_PLANET",
    "REG_TEXT_SOCIAL_BOOKS_GOODREADS":                      "MUL_TEXT_BOOKS_GOODREADS",
    "REG_TEXT_SOCIAL_BOOK_READABILITY_CLEAR":               "REG_TEXT_BOOK_READABILITY",
    "REG_TEXT_SOCIAL_KOREAN_DRAMA":                         "MUL_TEXT_KOREAN_DRAMA",
    "REG_TEXT_SOCIAL_MOVIES_DATASET_REVENUE":               "MUL_TEXT_BOX_OFFICE",
    "REG_TEXT_SOCIAL_MOVIES_ROTTEN_TOMATOES":               "REG_TEXT_ROTTEN_TOMATOES",
    "REG_TEXT_SOCIAL_VIDEO_GAMES_SALES":                    "REG_TEXT_VIDEO_GAMES_SALES",
    "REG_TEXT_SPORTS_FIFA22_WAGES":                         "REG_TEXT_FIFA22_WAGES",
    "REG_TEXT_TRANSPORTATION_USED_CAR_PAKISTAN":            "REG_TEXT_USED_CAR_PAKISTAN",
    "REG_TEXT_TRANSPORTATION_USED_CAR_SAUDI_ARABIA":        "REG_TEXT_USED_CAR_SAUDI",
}

# Candidates that were never released, so they have no name in do_dataset_summary.
_UNRELEASED_NAMES = {
    "MUL_TEXT_FOOD_YELP_REVIEWS":                           "Yelp Reviews",
    "MUL_TEXT_SOCIAL_GOOGLE_QA_TYPE_REASON":                "Google QA",
    "MUL_TEXT_SOCIAL_HEARTHSTONE_CARD_GAME_WARCRAFT":       "Hearthstone Cards",
    "REG_TEXT_CONSUMER_BIKE_PRICE_BIKEWALE":                "BikeWale Bikes",
    "REG_TEXT_CONSUMER_CAR_PRICE_CARDEKHO":                 "CarDekho Cars",
    "REG_TEXT_CONSUMER_JC_PENNEY_PRODUCT_PRICE":            "JC Penney",
    "REG_TEXT_CONSUMER_LAPTOP_INDIAN_PRICES":               "Indian Laptops",
    "REG_TEXT_FOOD_BEER_RATINGS":                           "Beer Ratings",
    "REG_TEXT_FOOD_COFFEE_REVIEW":                          "Coffee Reviews",
    "REG_TEXT_HOUSES_SAN_FRANCISCO_PERMITS_APPLICATIONS":   "SF Permits",
    "REG_TEXT_PROFESSIONAL_COMPANY_EMPLOYEES_SIZE":         "Company Size",
    "REG_TEXT_PROFESSIONAL_ML_DS_AI_JOBS_SALARIES":         "AI Job Salaries",
    "REG_TEXT_SOCIAL_FILMTV_MOVIE_RATING_ITALY":            "FilmTV Ratings",
    "REG_TEXT_SOCIAL_MUSEUMS_US_REVENUES":                  "US Museums",
    "REG_TEXT_SPORTS_NBA_DRAFT_VALUE_OVER_REPLACEMENT":     "NBA Draft Value",
    "REG_TEXT_TRANSPORTATION_USED_CAR_MERCEDES_BENZ_ITALY": "Used Cars Mercedes",
}

_RELEASED_NAMES = {**_FRIENDLY_NAMES, **_FRIENDLY_NAMES_EXTRA_TEXT}

POOL_DISPLAY_NAMES = {
    **{pool: _RELEASED_NAMES[released] for pool, released in POOL_TO_RELEASED.items()},
    **_UNRELEASED_NAMES,
}
